using Microsoft.UI.Input;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Input;
using Microsoft.UI.Xaml.Shapes;

namespace Digi21.WinUI.Docking.Primitives;

/// <summary>
/// The draggable divider generated by a <see cref="SplitContainer"/> between two adjacent panes.
/// Dragging it transfers space between its two neighbors by updating their
/// <see cref="DockSite.RelativeSizeProperty"/> values.
/// </summary>
public partial class DockSplitter : Control
{
    /// <summary>Identifies the <see cref="Orientation"/> dependency property.</summary>
    public static readonly DependencyProperty OrientationProperty = DependencyProperty.Register(
        nameof(Orientation),
        typeof(Orientation),
        typeof(DockSplitter),
        new PropertyMetadata(Orientation.Horizontal, (d, _) => ((DockSplitter)d).UpdateVisuals()));

    private Pointer? capturedPointer;
    private double startPosition;
    private double startNearSize;
    private double startFarSize;
    private double pairRelative;

    /// <summary>Initializes a new instance of the <see cref="DockSplitter"/> class.</summary>
    public DockSplitter()
    {
        DefaultStyleKey = typeof(DockSplitter);
        DefaultStyleResourceUri = new Uri("ms-appx:///Digi21.WinUI.Docking/Themes/Generic.xaml");
    }

    /// <summary>
    /// Gets or sets the orientation of the owning <see cref="SplitContainer"/>. A splitter in a
    /// horizontal container is a vertical bar dragged sideways, and vice versa.
    /// </summary>
    public Orientation Orientation
    {
        get => (Orientation)GetValue(OrientationProperty);
        set => SetValue(OrientationProperty, value);
    }

    internal SplitContainer? Owner { get; set; }

    internal int Index { get; set; }

    private bool IsDragging => capturedPointer is not null;

    /// <inheritdoc />
    protected override void OnApplyTemplate()
    {
        base.OnApplyTemplate();
        UpdateVisuals();
        VisualStateManager.GoToState(this, "Normal", false);
    }

    /// <inheritdoc />
    protected override void OnPointerEntered(PointerRoutedEventArgs e)
    {
        base.OnPointerEntered(e);
        VisualStateManager.GoToState(this, IsDragging ? "Pressed" : "PointerOver", true);
    }

    /// <inheritdoc />
    protected override void OnPointerExited(PointerRoutedEventArgs e)
    {
        base.OnPointerExited(e);
        VisualStateManager.GoToState(this, IsDragging ? "Pressed" : "Normal", true);
    }

    /// <inheritdoc />
    protected override void OnPointerPressed(PointerRoutedEventArgs e)
    {
        base.OnPointerPressed(e);

        if (Owner is null || !e.GetCurrentPoint(this).Properties.IsLeftButtonPressed)
        {
            return;
        }

        var panes = Owner.GetPanes();
        if (Index + 1 >= panes.Count)
        {
            return;
        }

        if (!CapturePointer(e.Pointer))
        {
            return;
        }

        var near = panes[Index];
        var far = panes[Index + 1];
        var horizontal = Orientation == Orientation.Horizontal;
        var position = e.GetCurrentPoint(Owner).Position;

        capturedPointer = e.Pointer;
        startPosition = horizontal ? position.X : position.Y;
        startNearSize = horizontal ? near.ActualSize.X : near.ActualSize.Y;
        startFarSize = horizontal ? far.ActualSize.X : far.ActualSize.Y;
        pairRelative = SplitContainer.GetEffectiveRelativeSize(near) + SplitContainer.GetEffectiveRelativeSize(far);

        VisualStateManager.GoToState(this, "Pressed", true);
        e.Handled = true;
    }

    /// <inheritdoc />
    protected override void OnPointerMoved(PointerRoutedEventArgs e)
    {
        base.OnPointerMoved(e);

        if (!IsDragging || Owner is null)
        {
            return;
        }

        var panes = Owner.GetPanes();
        if (Index + 1 >= panes.Count)
        {
            return;
        }

        var pairPixels = startNearSize + startFarSize;
        if (pairPixels < 2 * SplitContainer.MinPaneSize)
        {
            return;
        }

        var horizontal = Orientation == Orientation.Horizontal;
        var position = e.GetCurrentPoint(Owner).Position;
        var delta = (horizontal ? position.X : position.Y) - startPosition;

        var newNearSize = Math.Clamp(
            startNearSize + delta,
            SplitContainer.MinPaneSize,
            pairPixels - SplitContainer.MinPaneSize);

        var nearRelative = pairRelative * newNearSize / pairPixels;
        DockSite.SetRelativeSize(panes[Index], nearRelative);
        DockSite.SetRelativeSize(panes[Index + 1], pairRelative - nearRelative);

        e.Handled = true;
    }

    /// <inheritdoc />
    protected override void OnPointerReleased(PointerRoutedEventArgs e)
    {
        base.OnPointerReleased(e);

        if (IsDragging)
        {
            ReleasePointerCapture(e.Pointer);
            e.Handled = true;
        }
    }

    /// <inheritdoc />
    protected override void OnPointerCaptureLost(PointerRoutedEventArgs e)
    {
        base.OnPointerCaptureLost(e);
        capturedPointer = null;
        VisualStateManager.GoToState(this, "Normal", true);
    }

    private void UpdateVisuals()
    {
        var horizontal = Orientation == Orientation.Horizontal;

        ProtectedCursor = InputSystemCursor.Create(
            horizontal ? InputSystemCursorShape.SizeWestEast : InputSystemCursorShape.SizeNorthSouth);

        if (GetTemplateChild("GripLine") is Rectangle grip)
        {
            if (horizontal)
            {
                grip.Width = 1;
                grip.Height = double.NaN;
                grip.HorizontalAlignment = HorizontalAlignment.Center;
                grip.VerticalAlignment = VerticalAlignment.Stretch;
            }
            else
            {
                grip.Width = double.NaN;
                grip.Height = 1;
                grip.HorizontalAlignment = HorizontalAlignment.Stretch;
                grip.VerticalAlignment = VerticalAlignment.Center;
            }
        }
    }
}
